---
- name: Disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Remove old resolv.conf
  ansible.builtin.file:
    path: "/etc/resolv.conf"
    state: absent

- name: Upload custom resolv.conf
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"

- name: Install dnsmasq
  ansible.builtin.apt:
    name:
      - dnsmasq
      - dnsutils
      - ldnsutils

- name: Upload configurations
  ansible.builtin.template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"

- name: Enable dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted