all:
  hosts:
    master:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-master/virtualbox/private_key
      ansible_ssh_port: 2222
      ip: 192.168.0.201
      access_ip: 192.168.0.201
    worker1:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-worker1/virtualbox/private_key
      ansible_ssh_port: 2223
      ip: 192.168.0.202
      access_ip: 192.168.0.202
      node_labels:
        node-role.kubernetes.io/worker: ""
    worker2:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-worker2/virtualbox/private_key
      ansible_ssh_port: 2224
      ip: 192.168.0.203
      access_ip: 192.168.0.203
      node_labels:
        node-role.kubernetes.io/worker: ""
    ingress1:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/k8s-ingress1/virtualbox/private_key
      ansible_ssh_port: 2225
      ip: 192.168.0.204
      access_ip: 192.168.0.204
      node_labels:
        node-role.kubernetes.io/ingress: ""
      node_taints:
        - "node-role.kubernetes.io/ingress=:NoSchedule"
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker1:
        worker2:
        ingress1:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}